INSERT INTO herramientas (nombre, precio, stock) VALUES ('Martillo',150.00,20);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Desarmador Plano',80.00,35);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Desarmador Phillips',85.00,40);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Pinzas',120.00,25);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Llave Inglesa',200.00,15);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Taladro',1500.00,10);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Sierra Circular',2300.00,8);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Flexómetro',60.00,50);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Nivel',180.00,18);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Cincel',90.00,22);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Mazo',250.00,12);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Broca 1/4',35.00,60);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Broca 1/2',55.00,55);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Juego de Llaves',650.00,10);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Escalera',1800.00,5);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Pala',220.00,17);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Pico',280.00,14);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Carretilla',950.00,7);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Lijadora',1750.00,6);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Pulidora',1950.00,9);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Soldadora',4200.00,4);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Compresor',5800.00,3);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Remachadora',350.00,11);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Llave Stilson',420.00,13);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Cortadora',2600.00,6);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Segueta',75.00,30);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Prensa',380.00,8);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Escuadra',95.00,28);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Cepillo',140.00,16);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Tenaza',110.00,21);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Llana',125.00,19);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Espátula',65.00,32);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Cutter',45.00,45);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Sargento',170.00,12);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Multímetro',950.00,8);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Detector de Voltaje',220.00,14);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Pistola de Calor',890.00,9);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Generador',12000.00,2);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Bomba de Agua',3200.00,4);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Hidrolavadora',4500.00,3);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Motosierra',3800.00,5);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Podadora',2900.00,4);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Aspiradora Industrial',5200.00,2);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Extensión 10m',250.00,20);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Extensión 20m',390.00,15);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Caja de Herramientas',780.00,10);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Organizador',320.00,18);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Candado',145.00,30);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Cadena',260.00,16);
INSERT INTO herramientas (nombre, precio, stock) VALUES ('Reflector LED',540.00,12);

